/**
 ** @file	Main Page for Doxygen documentation.
 ** @brief	This file contains the main documentation page
 **
 ** The contents of this file will appear on the main page of the
 ** Arithmos deocumentation generated by doxygen.
 **
 ** $Id: MainPage.hh,v 1.1 2001/04/25 13:47:54 jvvloet Exp $
 ** $Date: 2001/04/25 13:47:54 $
 ** $Author: jvvloet $
 **/

/**
 ** @mainpage The Arithmos Library
 **
 ** Where do you want to go ?
 **
 **  - specific information for the rational Library (http://win-www.uia.ac.be/u/cant/arithmos/doxygen/indexRational.html)
 **  - overview of the classes in the library (http://win-www.uia.ac.be/u/cant/arithmos/doxygen/hierarchy.html)
 **/
